# External funding links shown by GitHub's Sponsor button.
buy_me_a_coffee: kevinlabs26
ko_fi: kevinlabs
custom:
  - https://kevinlabs.lemonsqueezy.com/checkout/buy/7b60b363-50b5-4233-a982-91a0611eccd6
